package com.gacagebot.localizestrings

enum class StringId(val id: String) {
    ACTIVITY_DJ_G_CAGE("ACTIVITY_DJ_G_CAGE"),
    MEETINGS_FIRST_JOIN_IN_THE_SERVER("MEETINGS_FIRST_JOIN_IN_THE_SERVER"),
    INVALID_COMMAND("INVALID_COMMAND"),
    SONG_IS_ALREADY_IN_QUEUE("SONG_IS_ALREADY_IN_QUEUE"),
    PLAYBACK_QUEUE_IS_EMPTY_CLEAR("PLAYBACK_QUEUE_IS_EMPTY_CLEAR"),
    MUSIC_WAS_PAUSED("MUSIC_WAS_PAUSED"),
    MUSIC_IS_PLAYING("MUSIC_IS_PLAYING"),
    LEAVE_FROM_VOICE_CHANNEL("LEAVE_FROM_VOICE_CHANNEL"),
    JOIN_VOICE_CHANNEL("JOIN_VOICE_CHANNEL"),
    LEAVE_DISCORD_SERVER("LEAVE_DISCORD_SERVER"),
    FAILED_JOIN_CHANNEL_YOU_NOT_IN_VOICE_CHANNEL("FAILED_JOIN_CHANNEL_YOU_NOT_IN_VOICE_CHANNEL"),
    FAILED_JOIN_CHANNEL_BOT_IS_ALREADY_IN_THIS_CHANNEL("FAILED_JOIN_CHANNEL_BOT_IS_ALREADY_IN_THIS_CHANNEL"),
    FAILED_JOIN_CHANNEL_UNABLE_TO_JOIN_THE_VOICE_CHANNEL("FAILED_JOIN_CHANNEL_UNABLE_TO_JOIN_THE_VOICE_CHANNEL"),
    FAILED_LEAVE_CHANNEL_BOT_IS_NOT_IN_ANY_VOICE_CHANNEL("FAILED_LEAVE_CHANNEL_BOT_IS_NOT_IN_ANY_VOICE_CHANNEL"),
    FAILED_PLAY_TRACK_CANNOT_FIND_THIS_MUSIC("FAILED_PLAY_TRACK_CANNOT_FIND_THIS_MUSIC"),
    FAILED_PLAY_TRACK_THIS_TRACK_IS_NOT_AVAILABLE_IN_YOUR_REGION("FAILED_PLAY_TRACK_THIS_TRACK_IS_NOT_AVAILABLE_IN_YOUR_REGION"),
    FAILED_PLAYBACK_ERROR("FAILED_PLAYBACK_ERROR"),
    UNEXPECTED_ERROR("UNEXPECTED_ERROR")
}